version: '3'
services:
  backend:
    container_name: backend
    volumes:
      - ./:/src
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"